apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-slim-deployment
  labels:
    tier: backend
    app: python
spec:
  selector:
    matchLabels:
      app: python
  replicas: 2
  template:
    metadata:
      name: python-slim-2
      labels:
        app: python
    spec:
      containers:
        - name: python-3-11-slim
          image: python:3.11-slim
